  # docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      command: >
        bash -c
        "apt-get update
        && apt-get -qy full-upgrade
        && apt-get install -qy curl
        && curl -sSL https://get.docker.com/ | sh
        && /usr/local/bin/jenkins.sh"
      ports:
       - 8080:8080
       - 8081:8081
       - 50000:50000
      container_name: jenkins
      volumes:
        - ./jenkins_volume:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock